server:
  port: 5555

spring:
  application:
    name: gateway

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 16000

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  retryableStatusCodes: 404, 500

zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    newsservice: /news/**
  retryable: true

management:
  endpoints:
    web:
      exposure:
        include: routes